# Generated by Django 6.0.4 on 2026-04-29 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Наш колледж"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstagramPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("photo", "Фото"),
                            ("video", "Видео"),
                            ("reels", "Reels"),
                            ("story", "Story"),
                        ],
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                ("likes", models.IntegerField(default=0, verbose_name="Лайки")),
                (
                    "comments",
                    models.IntegerField(default=0, verbose_name="Комментарии"),
                ),
                ("reach", models.IntegerField(default=0, verbose_name="Охват")),
                ("date", models.DateTimeField(verbose_name="Дата публикации")),
                ("caption", models.TextField(blank=True, verbose_name="Подпись")),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.college",
                        verbose_name="Колледж",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("2gis", "2GIS"), ("google", "Google")],
                        max_length=10,
                        verbose_name="Источник",
                    ),
                ),
                ("rating", models.IntegerField(verbose_name="Оценка (1-5)")),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                ("author", models.CharField(max_length=255, verbose_name="Автор")),
                ("date", models.DateTimeField(verbose_name="Дата")),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Положительный"),
                            ("neutral", "Нейтральный"),
                            ("negative", "Отрицательный"),
                        ],
                        max_length=10,
                        verbose_name="Тональность",
                    ),
                ),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.college",
                        verbose_name="Колледж",
                    ),
                ),
            ],
        ),
    ]
